### ISSUE TITLE
New metric

### ISSUE THREAD

**Issue by marcolivierarsenault** [AleixoLucas42/duplicati-prometheus-exporter#1]
Could we get a metric that display the latest status. 

I would like to be able to know the latest status of a backup and differentiate 

Success, Warning, Error

Right now, AFAIK, we can only get Success and Error. via `duplicati_is_last_backup_failed` 

But based on the filter: `result` looks like you can get all 3 statuses

**Comment by AleixoLucas42** [comment]
> Could we get a metric that display the latest status.
> 
> I would like to be able to know the latest status of a backup and differentiate
> 
> Success, Warning, Error
> 
> Right now, AFAIK, we can only get Success and Error. via `duplicati_is_last_backup_failed`
> 
> But based on the filter: `result` looks like you can get all 3 statuses

In the code itself, when there is an error in the log, it forces the result metric to be "Fail", what result do you expect to find? If you can get an example of how to reproduce a result other than success I can check what I can do, the result is obtained from Data.ParsedResult in https://github.com/AleixoLucas42/duplicati-prometheus-exporter/blob/main/config/duplicati/duplicati-post-backup-example.json, when there is an error, it does not always return this data, so there is a condition to force the result to be "Fail"; but still, it may be that I did not test all the scenarios, if there is an example for reproduction I can adjust the code

**Comment by AleixoLucas42** [comment]
Would it be something like this that you expect? I can just put numeric values ​​in the metrics, I made this implementation just to validate, assign for success = 0, warning = 1, fail = 2. The new metric is `duplicati_ops_result`

Dash:
![image](https://github.com/user-attachments/assets/1a379727-4232-46c7-9bfa-9d223bbd2f0e)
Panel:
![image](https://github.com/user-attachments/assets/aaae56f5-9480-4387-b236-6baa8ff4506a)
Metrics:
![image](https://github.com/user-attachments/assets/7d1d6e18-3b26-4643-810e-62369948001f)

**Comment by marcolivierarsenault** [comment]
Yep that would be great, I am doing exactly this but I only have good and error, not warning.

**Comment by marcolivierarsenault** [comment]
BTW, sick dashboard I applied a state chart, which I think is nice 
![image](https://github.com/user-attachments/assets/bc8ef71e-38e1-4f77-8624-2f46588516a8)

**Comment by AleixoLucas42** [comment]
> Yep that would be great, I am doing exactly this but I only have good and error, not warning.

I'm going to merge the branch I made the new metric so you can try on your side (:

**Comment by marcolivierarsenault** [comment]
Thanks a lot
